### ISSUE TITLE
Größenoptimierung

### ISSUE THREAD

**Issue by L3P3** [LFF5644/Wecker#12]
# IST

Der ganze Code ist in einer einzigen HTML-Datei. Diese wird genauso ausgeliefert wie geschrieben.

# SOLL

Der Code soll in separate CSS- und JS-Dateien aufgeteilt werden.
Es soll einen Befehl geben, der diese dann zusammenfasst zu entweder:

- Einer einzigen HTML-Datei
- Einer HTML-Datei, einer CSS-Datei und einer JS-Datei

Das Ergebnis sollte möglichst klein sein.

**Comment by LFF5644** [comment]
ok ich arbeite drann das nicht alles in einer datei ist

**Comment by L3P3** [comment]
Siehe letzte Zeile. Ein Befehl soll zusammenfassen und das Ergebnis möglichst klein machen. Steht da so.

**Comment by LFF5644** [comment]
ja das kommt dann später noch
