### ISSUE TITLE
Anwendung verfügbar machen

### ISSUE THREAD

**Issue by L3P3** [LFF5644/Wecker#16]
Es soll eine URL geben, unter der sich die Anwendung öffnen lässt.
Wenn der Code in diesem Repo verändert wird, soll automatisch die Anwendung den neuesten Stand haben.

**Comment by LFF5644** [comment]
zum `git pull` [api aufrufen](https://lff.l3p3.de/server/git/gitPull.api)

**Comment by LFF5644** [comment]
sobal ein neuer commit kommt ist auch automatisch der neueste stand auf [lff.l3p3.de](https://lff.l3p3.de/p/Wecker/index.html) das dank der [api](https://lff.l3p3.de/server/git/gitPull.api)
