### ISSUE TITLE
Verdoppelung beim Ändern

### ISSUE THREAD

**Issue by L3P3** [LFF5644/Wecker#21]
Wenn man die App zum ersten Mal öffnet und vom schon vorhandenen Demo-Wecker die Farbe ändert und zurück geht, ist plötzlich ein zweiter Wecker in der Liste!

**Comment by LFF5644** [comment]
habe ich ausprobirt und habe nichts in der art gefunden es funktonirt alles wie es soll

**Comment by LFF5644** [comment]
ich lasse den issu noch offen
