### ISSUE TITLE
Bessere URL, Produktiv-Variante von lui

### ISSUE THREAD

**Issue by L3P3** [LFF5644/Wecker#23]
Erstell mal eine separate HTML-Datei, die eine bessere URL hat als "https://lff.l3p3.de/p/Wecker/index.html"!

In dieser Datei werden die JS- und CSS-Dateien absolut verlinkt, also z.B. mit `/p/Wecker/app.js`.

Und in dieser Datei benutz dann auch lui.js statt lui.dev.js, damit es noch etwas schneller ist!

Die HTML-Datei in diesem Repo soll unverändert bleiben, damit sich das Projekt auch lokal testen lässt!

**Comment by L3P3** [comment]
Dass du lui.legacy.js benutzt, bringt alleine noch gar nichts, die Datei ist unnötig größer als lui.js! Änder das lieber mal und mach das mit lui.legacy.js später.

Und wenn ich https://lff.l3p3.de/Wecker aufrufe, ist da noch die alte Datei. Hat `git pull` nicht geklappt?

**Comment by LFF5644** [comment]
hir die kürtzere url [zum Wecker](https://lff.l3p3.de/Wecker)

**Comment by L3P3** [comment]
Super, fehlt noch lui.js zu benutzen statt lui.legacy.js!
