### ISSUE TITLE
Weitere Eigenschaften

### ISSUE THREAD

**Issue by L3P3** [LFF5644/Wecker#9]
Wecker sollen noch ein paar weitere Eigenschaften haben. Mindestens sollen dazu kommen:

- Deaktiviert
- Tage/Wiederholen
- Farbe
- Alarm-Typ (Leise/Laut)

**Comment by LFF5644** [comment]
soll jeder wecker ne fabe haben?
oder wie meinst du das?

**Comment by L3P3** [comment]
:eye: :lips: :eye:

JA

**Comment by LFF5644** [comment]
So, fertig.
